import { Project, Inquiry, SiteSettings } from '../types';

export const INITIAL_SITE_SETTINGS: SiteSettings = {
  id: '00000000-0000-0000-0000-000000000001',
  site_name: 'Syntax',
  designer_name: 'Abdullah',
  designer_title: 'Graphics Designer & Visual Director',
  headline: 'Visual Design & High-Impact Digital Craft',
  bio: 'I’m Abdullah, a graphics designer focused on creating meaningful visual identities, digital experiences and engaging creative content. I combine clean design, strong visual communication and modern aesthetics to help brands present themselves with confidence.',
  years_experience: '5+',
  completed_works: '120+',
  satisfaction_rate: '99%',
  availability_status: 'Independent Practice • Available for Q2/Q3 Projects',
  contact_email: 'abdullahgorib22@gmail.com',
  location: 'Dhaka / Remote',
  avatar_url: '/assets/portrait.png',
  toolkit: [
    { name: 'Photoshop', icon: 'auto_fix_high' },
    { name: 'Illustrator', icon: 'draw' },
    { name: 'Figma', icon: 'dashboard_customize' },
    { name: 'After Effects', icon: 'animation' },
  ],
  social_links: [
    { platform: 'Behance', url: 'https://www.behance.net/happycrust' },
    { platform: 'Dribbble', url: 'https://dribbble.com' },
    { platform: 'LinkedIn', url: 'https://linkedin.com' },
    { platform: 'Instagram', url: 'https://instagram.com' },
    { platform: 'Facebook', url: 'https://facebook.com' },
    { platform: 'X / Twitter', url: 'https://x.com' },
  ],
  services_list: [
    {
      id: '1',
      number: '01 / Foundation',
      title: 'Brand Identity',
      description: 'Complete visual identity systems that create a consistent and memorable brand presence across physical and digital mediums.',
      tags: 'Logos • Typography • Styleguides',
      icon: 'corporate_fare',
    },
    {
      id: '2',
      number: '02 / Engagement',
      title: 'Social Media Poster Design',
      description: 'Eye-catching social media visuals designed to communicate clearly, command scroll attention, and engage modern audiences.',
      tags: 'Instagram • Events • Carousel Sets',
      icon: 'art_track',
    },
    {
      id: '3',
      number: '03 / Promotion',
      title: 'Banner Design',
      description: 'Professional digital and promotional banners designed for marketing campaigns, high-traffic websites and social platforms.',
      tags: 'Web Hero • Google Ads • Billboard Kits',
      icon: 'ad_units',
    },
    {
      id: '4',
      number: '04 / Conversion',
      title: 'Thumbnail Design',
      description: 'High-impact thumbnails designed to improve attention, click appeal, and audience retention for creators and media platforms.',
      tags: 'YouTube • Podcasts • Stream Covers',
      icon: 'play_circle',
    },
  ],
  updated_at: '2026-09-01T00:00:00.000Z',
};

export const INITIAL_PROJECTS: Project[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    title: 'Aura Creative System',
    slug: 'aura-creative-system',
    short_description: 'Complete stationery ecosystem, typographic hierarchy, debossed packaging, and luxury brand collateral guidelines.',
    full_description: 'Aura Creative required an uncompromising corporate visual identity system tailored for a luxury design consultancy. We engineered a dual-tone palette centered around ultra-matte obsidian and electric violet highlights, complete with hot-stamped stationery, debossed business collateral, custom typographic styling in Space Grotesk, and rigorous editorial guidelines across print and digital touchpoints.',
    category: 'Brand Identity',
    tags: ['Identity System', 'Stationery', 'Packaging', 'Typography'],
    client: 'Aura Creative Inc.',
    year: '2024',
    role: 'Lead Identity Designer & Art Director',
    services: 'Brand Guidelines, Stationery Design, Foil Stamping, Print Production',
    cover_image: '/assets/aura-stationery.png',
    featured: true,
    published: true,
    sort_order: 1,
    created_at: '2026-09-01T10:00:00Z',
    updated_at: '2026-09-20T10:00:00Z',
    gallery_images: [
      {
        id: 'img-1-1',
        project_id: '11111111-1111-1111-1111-111111111111',
        storage_path: '/assets/aura-stationery.png',
        alt_text: 'Aura Creative luxury stationery mockup',
        sort_order: 1,
      },
    ],
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    title: 'Synthesis Exhibition',
    slug: 'synthesis-exhibition',
    short_description: 'Editorial event identity, large-format museum screenprints, and dynamic motion sequences for Instagram campaigns.',
    full_description: 'An exploratory graphic series for the SYNTHESIS international digital art exhibition. The project juxtaposes strict Swiss typographic grids against iridescent 3D chrome ribbons, evoking tactile weightlessness and luminescent tension. Included high-impact exhibition posters, museum wayfinding signage, social teaser carousels, and kinetic typography sequences.',
    category: 'Poster Design',
    tags: ['Exhibition', 'Swiss Typo', '3D Motion', 'Print Design'],
    client: 'Synthesis Arts Foundation',
    year: '2024',
    role: 'Visual Director',
    services: 'Screenprints, Exhibition Posters, Motion Design, Social Campaign',
    cover_image: '/assets/synthesis-poster.png',
    featured: true,
    published: true,
    sort_order: 2,
    created_at: '2026-09-05T12:00:00Z',
    updated_at: '2026-09-22T14:30:00Z',
    gallery_images: [
      {
        id: 'img-2-1',
        project_id: '22222222-2222-2222-2222-222222222222',
        storage_path: '/assets/synthesis-poster.png',
        alt_text: 'Synthesis Exhibition typography poster preview',
        sort_order: 1,
      },
    ],
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    title: 'Lumina Digital Campaign',
    slug: 'lumina-digital-campaign',
    short_description: 'Multichannel promotional display banners, high-converting digital billboards, and refined beauty ecommerce aesthetics.',
    full_description: 'Comprehensive omnichannel visual campaign designed for Lumina skincare launch. Engineered 40+ variations across Google Display, social billboards, and web hero placements with lavender frosted glass aesthetic, micro-animations, and clean typography maximizing click-through conversion rates.',
    category: 'Banner Design',
    tags: ['Digital Ads', 'Display Banners', 'Ecommerce', 'Motion'],
    client: 'Lumina Skincare Zurich',
    year: '2024',
    role: 'Senior Digital Designer',
    services: 'Hero Banners, Google Display Ads, Social Media Visuals',
    cover_image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
    sort_order: 3,
    created_at: '2026-09-10T09:00:00Z',
    updated_at: '2026-09-24T11:00:00Z',
  },
  {
    id: '44444444-4444-4444-4444-444444444444',
    title: 'Visual Velocity',
    slug: 'visual-velocity',
    short_description: 'Editorial creator thumbnail engineering, high-contrast typography, and CTR-maximizing spatial compositions.',
    full_description: 'Curated suite of editorial thumbnails and promotional art for Visual Velocity technology series. Engineered high dynamic contrast, custom 3D typography, volumetric lighting effects, and focal points tailored for rapid audience comprehension in dense YouTube feeds, resulting in over 4 million impressions.',
    category: 'Thumbnail Design',
    tags: ['Thumbnails', 'High CTR', 'Creator Media', 'YouTube'],
    client: 'Velocity Media Group',
    year: '2023',
    role: 'Thumbnail Architect',
    services: 'YouTube Thumbnails, Video Packaging, Social Billboards',
    cover_image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
    sort_order: 4,
    created_at: '2026-09-12T15:00:00Z',
    updated_at: '2026-09-25T16:00:00Z',
  },
  {
    id: '55555555-5555-5555-5555-555555555555',
    title: 'Kroma Spatial Architecture',
    slug: 'kroma-spatial-architecture',
    short_description: 'Exploratory spatial environments, immersive 3D art direction, and dimensional branding for next-generation platforms.',
    full_description: 'Experimental spatial design project exploring virtual architectural pavilions and monolithic brand identities. Leveraging procedural geometric rendering, deep purple ambient lighting, and subtle atmospheric grain to create futuristic agency experiences.',
    category: 'Brand Identity',
    tags: ['3D Craft', 'Spatial', 'Architectural', 'Editorial'],
    client: 'Kroma Spatial Labs',
    year: '2024',
    role: '3D Art Director',
    services: '3D Concept Art, Spatial Branding, Editorial Lookbook',
    cover_image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
    featured: false,
    published: true,
    sort_order: 5,
    created_at: '2026-09-15T08:00:00Z',
    updated_at: '2026-09-26T18:00:00Z',
  },
];

export const INITIAL_INQUIRIES: Inquiry[] = [
  {
    id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    client_name: 'Abdur Rahman',
    email: 'rahman@auracreative.io',
    service_type: 'Brand Identity',
    budget: '$1,000 – $3,000',
    reference_url: 'https://auracreative.io',
    brief: 'We need a complete brand identity refresh for our creative agency including new logomarks, typography rules, and stationery.',
    notes: 'Prefers modern violet and matte black palette. Deadline in 3 weeks.',
    status: 'new',
    created_at: '2026-09-27T14:20:00Z',
  },
  {
    id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
    client_name: 'Nusrat Jahan',
    email: 'nusrat.vibe@agency.co',
    service_type: 'Social Media Poster Design',
    budget: '$500 – $1,000',
    reference_url: 'https://instagram.com/agency.vibe',
    brief: 'Series of 8 promotional carousel poster designs for an upcoming cultural music festival.',
    notes: 'Draft concepts submitted, awaiting client sign-off on color grading.',
    status: 'in_progress',
    created_at: '2026-09-26T11:15:00Z',
  },
  {
    id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    client_name: 'Elena Rostova',
    email: 'elena@fintechvision.io',
    service_type: 'Banner Design',
    budget: '$3,000 – $5,000',
    reference_url: 'https://fintechvision.io',
    brief: 'Full set of marketing display ads and website hero banners for our digital banking product launch.',
    notes: 'Initial review complete. Contract sent.',
    status: 'new',
    created_at: '2026-09-25T09:30:00Z',
  },
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
    client_name: 'Marcus Vance',
    email: 'marcus@creatornetwork.com',
    service_type: 'Thumbnail Design',
    budget: '$500 – $1,000',
    reference_url: 'https://youtube.com/@marcusvance',
    brief: 'Pack of 10 high-CTR YouTube tech series thumbnails with custom 3D typography and focal framing.',
    notes: 'Assets delivered and approved. Final payment processed.',
    status: 'completed',
    created_at: '2026-09-22T16:45:00Z',
  },
];
