/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: '#fcf8f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf8f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0edec',
        'surface-container-high': '#ebe7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#484456',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#797488',
        'outline-variant': '#cac3d9',
        'surface-tint': '#632ef6',
        primary: '#5308e7',
        'on-primary': '#ffffff',
        'primary-container': '#6c3bff',
        'on-primary-container': '#eae2ff',
        'inverse-primary': '#cbbeff',
        secondary: '#5f5c6e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2ddf3',
        'on-secondary-container': '#636073',
        tertiary: '#454f63',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#5d677c',
        'on-tertiary-container': '#dce6ff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e6deff',
        'primary-fixed-dim': '#cbbeff',
        'on-primary-fixed': '#1d0061',
        'on-primary-fixed-variant': '#4b00d4',
        'secondary-fixed': '#e4e0f5',
        'secondary-fixed-dim': '#c8c4d9',
        'on-secondary-fixed': '#1b1a29',
        'on-secondary-fixed-variant': '#474556',
        'tertiary-fixed': '#d9e3fb',
        'tertiary-fixed-dim': '#bdc7de',
        'on-tertiary-fixed': '#111c2d',
        'on-tertiary-fixed-variant': '#3d475a',
        background: '#fcf8f8',
        'on-background': '#1c1b1b',
        'surface-variant': '#e5e2e1'
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px'
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'space-2xl': '4rem',
        'space-3xl': '6rem',
        margin: '1.5rem',
        'margin-md': '3rem',
        'margin-lg': '5rem',
        gutter: '1.5rem',
        'gutter-lg': '2.5rem',
      },
      fontFamily: {
        'display-hero': ['"Space Grotesk"', 'sans-serif'],
        'headline-xl': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg': ['"Space Grotesk"', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'headline-sm': ['"Space Grotesk"', 'sans-serif'],
        'display-hero-mobile': ['"Space Grotesk"', 'sans-serif'],
        'headline-xl-mobile': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg-mobile': ['"Space Grotesk"', 'sans-serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'body-sm': ['"Hanken Grotesk"', 'sans-serif'],
        'label-md': ['"JetBrains Mono"', 'monospace'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
        sans: ['"Hanken Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        display: ['"Space Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '600' }],
        'display-hero-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', letterSpacing: '0.005em', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
      }
    },
  },
  plugins: [],
}
